/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class ExternalObject<T> {
  readonly '': {
    readonly '': unique symbol
    [K: symbol]: T
  }
}
export function normalize(input: string): string
export function resolve(inputs: Array<string>): string
export function relative(a: string, b: string): string
